<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>0.0.4</Version>
        <TargetFramework>net9.0-ios</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <IsBindingProject>true</IsBindingProject>
        <RepositoryUrl>https://github.com/Truvideo/truvideo-sdk-video-net</RepositoryUrl>
    </PropertyGroup>
    <ItemGroup>
        <ObjcBindingApiDefinition Include="ApiDefinition.cs"/>
        <ObjcBindingCoreSource Include="Structs.cs"/>
    </ItemGroup>
    <ItemGroup>
        <NativeReference Include="xcframeworks/TruvideoVideo.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/TruvideoSdkVideo.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/ffmpegkit.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/libavcodec.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/libavdevice.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/libavfilter.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/libavformat.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/libavutil.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/libswresample.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
        <NativeReference Include="xcframeworks/libswscale.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
    </ItemGroup>
</Project>